'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CodeRefactoring1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to String interpolation allows for better reading of the resulting string when compared to Console.WriteLine arguments. You should use Console.WriteLine with arguments only when another method is supplying the format string..
        '''</summary>
        Friend ReadOnly Property ConsoleWriteLineAnalyzer_Description() As String
            Get
                Return ResourceManager.GetString("ConsoleWriteLineAnalyzer_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use string interpolation.
        '''</summary>
        Friend ReadOnly Property ConsoleWriteLineAnalyzer_MessageFormat() As String
            Get
                Return ResourceManager.GetString("ConsoleWriteLineAnalyzer_MessageFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An empty catch block suppress all errors and shouldn&apos;t be used.\r\nIf the error is expected consider logging it or changing the control flow such that it is explicit..
        '''</summary>
        Friend ReadOnly Property EmptyCatchBlockAnalyzer_Description() As String
            Get
                Return ResourceManager.GetString("EmptyCatchBlockAnalyzer_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Empty Catch Block..
        '''</summary>
        Friend ReadOnly Property EmptyCatchBlockAnalyzer_Message() As String
            Get
                Return ResourceManager.GetString("EmptyCatchBlockAnalyzer_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Catch block cannot be empty.
        '''</summary>
        Friend ReadOnly Property EmptyCatchBlockAnalyzer_Title() As String
            Get
                Return ResourceManager.GetString("EmptyCatchBlockAnalyzer_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insert Exception class to Catch.
        '''</summary>
        Friend ReadOnly Property EmptyCatchBlockCodeFixProvider_InsertException() As String
            Get
                Return ResourceManager.GetString("EmptyCatchBlockCodeFixProvider_InsertException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove Empty Catch Block.
        '''</summary>
        Friend ReadOnly Property EmptyCatchBlockCodeFixProvider_Remove() As String
            Get
                Return ResourceManager.GetString("EmptyCatchBlockCodeFixProvider_Remove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove Empty Catch Block and Put a Documentation Link about Try...Catch use.
        '''</summary>
        Friend ReadOnly Property EmptyCatchBlockCodeFixProvider_RemoveAndDocumentation() As String
            Get
                Return ResourceManager.GetString("EmptyCatchBlockCodeFixProvider_RemoveAndDocumentation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove wrapping Try Block.
        '''</summary>
        Friend ReadOnly Property EmptyCatchBlockCodeFixProvider_RemoveTry() As String
            Get
                Return ResourceManager.GetString("EmptyCatchBlockCodeFixProvider_RemoveTry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove ByVal from function declaration.
        '''</summary>
        Friend ReadOnly Property RemoveByValDescription() As String
            Get
                Return ResourceManager.GetString("RemoveByValDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove ByVal from parameter {0}.
        '''</summary>
        Friend ReadOnly Property RemoveByValMessageFormat() As String
            Get
                Return ResourceManager.GetString("RemoveByValMessageFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove ByVal.
        '''</summary>
        Friend ReadOnly Property RemoveByValTitle() As String
            Get
                Return ResourceManager.GetString("RemoveByValTitle", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
