Namespace Roslyn.Utilities
    Friend Module GeneratedCodeUtilities
        Private ReadOnly s_autoGeneratedStrings() As String = {"<autogenerated", "<auto-generated"}

        Friend Function IsGeneratedSymbolWithGeneratedCodeAttribute(ByVal symbol As ISymbol, ByVal generatedCodeAttribute As INamedTypeSymbol) As Boolean
            Debug.Assert(symbol IsNot Nothing)
            Debug.Assert(generatedCodeAttribute IsNot Nothing)

            ' Don't check this for namespaces.  Namespaces cannot have attributes on them. And,
            ' currently, calling DeclaringSyntaxReferences on an INamespaceSymbol is more expensive
            ' than is desirable.
            If symbol.Kind <> SymbolKind.Namespace Then
                ' GeneratedCodeAttribute can only be applied once on a symbol.
                ' For partial symbols with more than one definition, we must treat them as non-generated code symbols.
                If symbol.DeclaringSyntaxReferences.Length > 1 Then
                    Return False
                End If

                For Each attribute As AttributeData In symbol.GetAttributes()
                    If DirectCast(generatedCodeAttribute, Object).Equals(attribute.AttributeClass) Then
                        Return True
                    End If
                Next attribute
            End If

            Return symbol.ContainingSymbol IsNot Nothing AndAlso IsGeneratedSymbolWithGeneratedCodeAttribute(symbol.ContainingSymbol, generatedCodeAttribute)
        End Function

        Friend Function IsGeneratedCode(ByVal tree As SyntaxTree, ByVal isComment As Func(Of SyntaxTrivia, Boolean), ByVal cancellationToken As CancellationToken) As Boolean
            Return IsGeneratedCodeFile(tree.FilePath) OrElse BeginsWithAutoGeneratedComment(tree, isComment, cancellationToken)
        End Function

        Private Function IsGeneratedCodeFile(ByVal filePath As String) As Boolean
            If Not String.IsNullOrEmpty(filePath) Then
                Dim fileName As String = IO.Path.GetFileName(filePath)
                If fileName.StartsWith("TemporaryGeneratedFile_", StringComparison.OrdinalIgnoreCase) Then
                    Return True
                End If

                Dim extension As String = IO.Path.GetExtension(filePath)
                If Not String.IsNullOrEmpty(extension) Then
                    Dim fileNameWithoutExtension As String = IO.Path.GetFileNameWithoutExtension(filePath)
                    If fileNameWithoutExtension.EndsWith(".designer", StringComparison.OrdinalIgnoreCase) OrElse fileNameWithoutExtension.EndsWith(".generated", StringComparison.OrdinalIgnoreCase) OrElse fileNameWithoutExtension.EndsWith(".g", StringComparison.OrdinalIgnoreCase) OrElse fileNameWithoutExtension.EndsWith(".g.i", StringComparison.OrdinalIgnoreCase) Then
                        Return True
                    End If
                End If
            End If

            Return False
        End Function

        Private Function BeginsWithAutoGeneratedComment(ByVal tree As SyntaxTree, ByVal isComment As Func(Of SyntaxTrivia, Boolean), ByVal cancellationToken As CancellationToken) As Boolean
            Dim root As SyntaxNode = tree.GetRoot(cancellationToken)
            If root.HasLeadingTrivia Then
                Dim leadingTrivia As SyntaxTriviaList = root.GetLeadingTrivia()

                For Each trivia As SyntaxTrivia In leadingTrivia
                    If Not isComment(trivia) Then
                        Continue For
                    End If

                    Dim text As String = trivia.ToString

                    ' Check to see if the text of the comment contains an auto generated comment.
                    For Each autoGenerated As String In s_autoGeneratedStrings
                        If text.Contains(autoGenerated) Then
                            Return True
                        End If
                    Next autoGenerated
                Next trivia
            End If

            Return False
        End Function
    End Module
End Namespace
